import type { DemoChallenge, PastCase } from "./types";

export const DEFAULT_CLAIM =
  "By 2030, AI will measurably lower the real cost of at least one of housing, healthcare, education, or childcare in the US.";

export const SEED_CHALLENGES: DemoChallenge[] = [
  {
    id: "q1",
    type: "question",
    upvotes: 14,
    hidden: false,
    author: "mira",
    text: 'What counts as "measurably"? A falling price index, or a cost study?',
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { answered: 0, partial: 0, dodged: 0 },
    narrowingRuling: null,
  },
  {
    id: "c1",
    type: "counterfact",
    upvotes: 11,
    hidden: false,
    author: "feld",
    text: "Real prices in all four sectors have outpaced inflation for decades. No technology has reversed that yet.",
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { convincing: 0, notConvincing: 0 },
    narrowingRuling: null,
  },
  {
    id: "q2",
    type: "question",
    upvotes: 9,
    hidden: false,
    author: "rhea",
    text: "Does it count if costs fall for providers but prices to families don't?",
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { answered: 0, partial: 0, dodged: 0 },
    narrowingRuling: null,
  },
  {
    id: "c2",
    type: "counterfact",
    upvotes: 7,
    hidden: true,
    author: "kaito",
    text: "Most healthcare cost is labor and regulation, which AI barely touches.",
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { convincing: 0, notConvincing: 0 },
    narrowingRuling: null,
  },
  {
    id: "q3",
    type: "question",
    upvotes: 12,
    hidden: true,
    author: "atlas_9",
    text: 'Which sector are you actually betting on? "Any of four" is hard to lose.',
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { answered: 0, partial: 0, dodged: 0 },
    narrowingRuling: null,
  },
  {
    id: "c3",
    type: "counterfact",
    upvotes: 8,
    hidden: false,
    author: "june",
    text: "Housing costs are driven by land and zoning, not construction efficiency.",
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { convincing: 0, notConvincing: 0 },
    narrowingRuling: null,
  },
  {
    id: "q4",
    type: "question",
    upvotes: 4,
    hidden: false,
    author: "soph",
    text: "Measured against what baseline year?",
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { answered: 0, partial: 0, dodged: 0 },
    narrowingRuling: null,
  },
  {
    id: "c4",
    type: "counterfact",
    upvotes: 6,
    hidden: false,
    author: "dr_lumen",
    text: "Some education prices were already falling online before AI, so a drop wouldn't prove AI caused it.",
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { convincing: 0, notConvincing: 0 },
    narrowingRuling: null,
  },
  {
    id: "q5",
    type: "question",
    upvotes: 5,
    hidden: true,
    author: "n_01",
    text: "How would you separate AI's effect from ordinary recession deflation?",
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { answered: 0, partial: 0, dodged: 0 },
    narrowingRuling: null,
  },
  {
    id: "c5",
    type: "counterfact",
    upvotes: 10,
    hidden: false,
    author: "ossie",
    text: "Consolidated hospital systems keep efficiency gains as margin instead of lowering prices.",
    round: null,
    resp: { text: "", mode: "", source: "", narrowed: "" },
    tally: { convincing: 0, notConvincing: 0 },
    narrowingRuling: null,
  },
];

/** A fixed illustrative record for the claimant's own history, shown on the
 * claim stage so the audience can judge how much weight to give them. */
export const CLAIMANT_PAST_RECORD: PastCase[] = [
  {
    claim: "Open-weight models will match the best closed model on a major coding benchmark by mid-2026",
    verdict: "Upheld",
    opening: 50,
    final: 64,
  },
  {
    claim: "A city will pass an AI-specific rent-setting ban before 2026",
    verdict: "Overturned",
    opening: 55,
    final: 44,
  },
  {
    claim: "An AI-discovered drug will enter phase 3 trials by 2027",
    verdict: "Amended",
    opening: 48,
    final: 51,
  },
];
